name: Azure SQL DB Deploy

on:
  push:
    branches:
      - new



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Azure CLI
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          
    - name: Deploy Azure SQL DB
      uses: azure/sql-action@v1
      with:
        server-name: sert.database.windows.net
        admin-login: azureuser
        admin-password: Devi@329
        database-name: mysql
        sql-file: ./AzureSQLDB.sqlproj
        connection-string: '${{ secrets.SQL_CONNECTION_STRING }}'

