name: Azure SQL DB Deploy

on:
  push:
    branches:
      - main


env:
  SERVER: sert
  DATABASE: mysql
  USERNAME: azureuser
  PASSWORD: Devi@329

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ${{ github.workspace }}/publish

    - name: Deploy to Azure SQL
      uses: azure/sql-action@v1
      with:
        server-name: ${{ env.SERVER }}
        database-name: ${{ env.DATABASE }}
        admin-login: ${{ env.USERNAME }}
        admin-password: ${{ env.PASSWORD }}
        azure-resource-group: docker-rg
        dacpac-package: ${{ github.workspace }}/publish/Create dacpac from ADS test.dacpac
